# Development config
development:
  redis:
    addr: 127.0.0.1:6389
    password: luowei2008
    db: 0

  log_file: "/Users/ning/go/src/github.com/lndj/school-helper/app_runtime.log"

# Production config
production:
  redis:
    addr: 127.0.0.1:6389
    password: luowei2008
    db: 0

  log_file: "/home/caddy_logs/app_runtime.log"
